### PR TITLE
Additional speedup from stricter format

### PR DESCRIPTION
**Pull request by 197g**
First of all, this breaks with exact behaviour php script but only as covered by the documentation of xdebug: https://xdebug.org/docs/execution_trace#trace-format. The begin and end marker are surely at the beginning of a line and all other separators are specified as tabs.

Handrolled string split, as the standard library version does not know
that we split by an ascii symbol (and hence don't require checks for 
utf-8 boundaries) and the optimizer doesn't quite propagate the constant 
argument well enough. And replaced the regex detection from begin and
end with simple string begin tests, as the spec apparently guarantees 
this.

And finally, the documentation pass also added some comments for the previous changes :grinning:

### CODE REVIEW

**Comment by daniellockyer** [comment]
@HeroicKatora WOW! We're now down to about 91ms on my machine, or about 10x faster! Absolutely excellent work.

Can I ask that you run `clippy` over it? I only see 4 points but then we should be good to go.

**Comment by Jetroid** [comment]
Wow @HeroicKatana, great work!

**Comment by HeroicKatana** [comment]
Mentioned the wrong person lol bye bye guys 😂

**Comment by 197g** [comment]
@neosilky I think I allowed you to push edits to the branch as well but will run clippy myself when I get to it.

**Pull request merged**
