### PR TITLE
Remove allocations through interning and speedup hashing

### PR DESCRIPTION
**Pull request by 197g**
The main changes are these:

* Function names are `interned`. That means that we generate a short, unique key for each name so that looking it up in a `HashMap` only requires hashing of the short key instead of the complete string. This extends to using a `slice` of these keys, representing the current call stack, as keys instead of a long concatenated string representation.
* The generation of the display name that is written to out is delayed until the very end, instead of being computed each time the call stack changes. This avoids many allocations.

### CODE REVIEW

**Comment by 197g** [comment]
Anyone reading this, feel free to comment. Any additional suggestions and improvements, or bugfixes are going to be taken into account tomorrow. @neosilky  I didn't know how to properly test these changes, any suggestsions?

The allocations in the lookups at `call_without_path` should really not be necessary, I'm not sure how to remove the one in `call_with_path` as even `HashMap::get` requires `(String, String): Borrow<K>` and there is not type which is `(String, String): Borrow<K>` afaik. Ideas are welcome.

**Comment by 197g** [comment]
Closing this until I find the speed tests etc.

**Comment by daniellockyer** [comment]
Hi @HeroicKatora!

In terms of testing, I've been running this program against the original `stackcollapse-xdebug.php` and comparing the output. In terms of benchmarking, I've been using `hyperfine` in the following way:

```bash
hyperfine "./target/release/inferno-collapse-xdebug xdebug.trace.xt > /dev/null" "./flamegraph/stackcollapse-xdebug.php xdebug.trace.xt > /dev/null"
```

I'll grab a copy of these changes and see what effect they have.

**Comment by daniellockyer** [comment]
Nice one @HeroicKatora! Shall I reopen and we can look at getting this merged?

```
Benchmark #1: ./target/release/inferno-collapse-xdebug xdebug.trace.xt > /dev/null
  Time (mean ± σ):     214.3 ms ±  13.2 ms    [User: 198.3 ms, System: 14.0 ms]
  Range (min … max):   198.9 ms … 237.7 ms    12 runs

Benchmark #2: ./flamegraph/stackcollapse-xdebug.php xdebug.trace.xt > /dev/null
  Time (mean ± σ):      1.010 s ±  0.030 s    [User: 943.4 ms, System: 57.0 ms]
  Range (min … max):    0.967 s …  1.057 s    10 runs

Summary
  './target/release/inferno-collapse-xdebug xdebug.trace.xt > /dev/null' ran
    4.71 ± 0.32 times faster than './flamegraph/stackcollapse-xdebug.php xdebug.trace.xt > /dev/null'
```

**Comment by 197g** [comment]
@neo Ah yes, let's reopen this with some more potential improvements.

**Comment by HeroicKatora** [comment]
So, if this is not even better, you tell me and I revert to the exact commit when I closed this.

**Comment by 197g** [comment]
The question is mostly: Is this faster than other Rust versions, not so much only a comparison against php. How large is the stack trace btw, I haven't managed to get my hands on one with a reasonable load.

**Comment by daniellockyer** [comment]
@HeroicKatora It's definitely the fastest I've seen so far. Current `master` is around 3.7x faster than PHP and this is around 4.7x.

I have a 22MB (~320,000 lines) one that I've been using for the tests. It's from a client's WordPress site but feel free to email me if you want a copy of it.

**Comment by neo** [comment]
Mentioned the wrong person lol bye bye guys 😂

**Comment by 197g** [comment]
@neosilky (this time the correct ping). Probably got another nice speedup?

**Comment by daniellockyer** [comment]
@HeroicKatora Excellent! Showing as 5x faster than PHP & the fastest I've seen so far.

It all looks good to me so let me know when you feel like you're done and I can merge. Please run `cargo fmt` over it too.

Thanks!

**Comment by 197g** [comment]
@neosilky All ready, still feels like it could somehow be more efficient but can't find anything else for now.

**Pull request merged**
